// Exemption Codes
// Code	Description
export default {
    'EX-XA': '11.111 Public property for housing indigent persons.',
    'EX-XD': '11.181 Improving property for housing with volunteer labor.',
    'CHODO': '11.182 Community Housing Development Organizations.',
    'EX-XF': '11.183 Assisting ambulatory health care centers.',
    'EX-XG': '11.184 Primarily performing charitable functions.',
    'EX-XH': '11.185 Developing model colonia subdivisions.',
    'EX-XI': '11.19 Youth spiritual, mental, and physical development organizations.',
    'EX-XJ': '11.21 Private schools.',
    'EX-XU': '11.23 Miscellaneous Exemptions.',
    'EX-XL': '11.231 Organizations Providing Economic Development Services to Local Community.',
    'EX-XM': '11.25 Marine cargo containers.',
    'EX-XN': '11.252 Motor vehicles leased for personal use.',
    'EX-XO': '11.254 Motor vehicles for income production and personal use.',
    'EX-XP': '11.271 Offshore drilling equipment not in use.',
    'EX-XQ': '11.29 Intracoastal waterway dredge disposal site.',
    'EX-XR': '11.30 Nonprofit water or wastewater corporation.',
    'EX-XS': '11.33 Raw cocoa and green coffee held in Harris County.',
    'EX-XT': '11.34 Limitation on taxes in certain municipalities.',
    'AB': 'Abatement.',
    'ABMNO': 'Abatement-MNO Only.',
    'CH': 'Charitable.',
    'CLT': 'Community Land Trust.',
    'DP': 'Disability.',
    'DPS': 'DISABLED Surviving Spouse.',
    'DVCH': 'Disabled Veteran Charity Homestead.',
    'DVCHS': 'Disabled Veteran Charity Homestead Surviving Spouse.',
    'DVHS': 'Disabled Veteran Homestead.',
    'DVHSS': 'Disabled Veteran Homestead Surviving Spouse.',
    'DV1': 'Disabled Veterans 10% - 29%.',
    'DV2': 'Disabled Veterans 30% - 49%.',
    'DV3': 'Disabled Veterans 50% - 69%.',
    'DV4': 'Disabled Veterans 70% - 100%.',
    'DV1S': 'Disabled Veterans Surviving Spouse 10% - 29%.',
    'DV2S': 'Disabled Veterans Surviving Spouse 30% - 49%.',
    'DV3S': 'Disabled Veterans Surviving Spouse 50% - 69%.',
    'DV4S': 'Disabled Veterans Surviving Spouse 70% - 100%.',
    'DSTR': 'Disaster Damage Exemption.',
    'LVE': 'Do Not USE Leased Vehicles.',
    'ECO': 'Economic Development.',
    'EN': 'Energy.',
    'AG': 'EOY:AG.',
    'EX': 'Exempt.',
    'FRSS': 'First Responder Surviving Spouse.',
    'FR': 'Freeport.',
    'GIT': 'GOODS IN TRANSIT.',
    'EX366': 'HB366 Exempt.',
    'HT': 'Historical.',
    'HS': 'Homestead.',
    'MASSS': 'Member Armed Services Surviving Spouse.',
    'EX-XV': 'Other Exemptions (including public property, religious organizations, charitable organizations, and other property not reported elsewhere).',
    'PPV': 'Personal Property Vehicle.',
    'PC': 'Pollution Control.',
    'LIH': 'Public property for housing indigent persons.',
    'SO': 'Solar.',
    'OTHER': 'Exemption not listed.'
}
